[tool.poetry]
name = "django-test"
version = "0.1.0"
description = ""
authors = ["Ismael Arce"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
